"""
Django settings for voting_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# ═══════════════════════════════════════════════
# BASE DIRECTORY
# ═══════════════════════════════════════════════
BASE_DIR = Path(__file__).resolve().parent.parent

# ═══════════════════════════════════════════════
# DATABASE
# ═══════════════════════════════════════════════
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# ═══════════════════════════════════════════════
# SECURITY SETTINGS
# ═══════════════════════════════════════════════

SECRET_KEY = 'django-insecure-abc123xyz456'

DEBUG = 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',   # Render deploy support
]


# ═══════════════════════════════════════════════
# INSTALLED APPS
# ═══════════════════════════════════════════════
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'voting_app',
]


# ═══════════════════════════════════════════════
# MIDDLEWARE
# ═══════════════════════════════════════════════
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise (Static files serve karega)
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'voting_system.urls'


# ═══════════════════════════════════════════════
# TEMPLATES
# ═══════════════════════════════════════════════
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voting_system.wsgi.application'


# ═══════════════════════════════════════════════
# DATABASE
# ═══════════════════════════════════════════════



# ═══════════════════════════════════════════════
# PASSWORD VALIDATION
# ═══════════════════════════════════════════════
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
     'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ═══════════════════════════════════════════════
# INTERNATIONALIZATION
# ═══════════════════════════════════════════════
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# ═══════════════════════════════════════════════
# STATIC FILES (FIXED ✔️)
# ═══════════════════════════════════════════════
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'voting_app' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage (important)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ═══════════════════════════════════════════════
# MEDIA FILES (optional but useful)
# ═══════════════════════════════════════════════
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ═══════════════════════════════════════════════
# EMAIL CONFIGURATION (OTP ready ✔️)
# ═══════════════════════════════════════════════
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'singh2005any@gmail.com'        # 👉 apna Gmail
EMAIL_HOST_PASSWORD = 'gyyylzjymwigzdic'   # 👉 App Password (NOT normal password)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# ═══════════════════════════════════════════════
# OTP SETTINGS (ADDED ✔️)
# ═══════════════════════════════════════════════
OTP_EXPIRY_TIME = 300      # 5 minutes
OTP_MAX_ATTEMPTS = 5


# ═══════════════════════════════════════════════
# SESSION SETTINGS
# ═══════════════════════════════════════════════
SESSION_COOKIE_AGE = 3600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True


# ═══════════════════════════════════════════════
# SECURITY HEADERS (IMPROVED ✔️)
# ═══════════════════════════════════════════════
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ═══════════════════════════════════════════════
# DEFAULT AUTO FIELD
# ═══════════════════════════════════════════════
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ═══════════════════════════════════════════════
# MESSAGES FRAMEWORK
# ═══════════════════════════════════════════════
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}