# Generated by Django 6.0.2 on 2026-04-15 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_election'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['serial_no'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-created_at'], 'verbose_name': 'Election', 'verbose_name_plural': 'Elections'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting_app.election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before candidate appears on ballot'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_symbol',
            field=models.URLField(blank=True, help_text='Party symbol image URL'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='serial_no',
            field=models.PositiveIntegerField(default=1, help_text='Ballot order number'),
        ),
        migrations.AddField(
            model_name='election',
            name='allow_revote',
            field=models.BooleanField(default=False, help_text='Allow changing vote?'),
        ),
        migrations.AddField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='election',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible to voters?'),
        ),
        migrations.AddField(
            model_name='election',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='max_voters',
            field=models.PositiveIntegerField(blank=True, help_text='Cap on total voters (leave blank = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='election',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='voting_app.election'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Admin can flag suspicious votes for review'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.URLField(blank=True, help_text='Candidate photo URL'),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_time',
            field=models.DateTimeField(help_text='Use IST (Asia/Kolkata)'),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Master on/off switch'),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_time',
            field=models.DateTimeField(help_text='Use IST (Asia/Kolkata)'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'serial_no')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'election')},
        ),
        migrations.CreateModel(
            name='ElectionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Election Created'), ('updated', 'Election Updated'), ('started', 'Election Started'), ('paused', 'Election Paused'), ('ended', 'Election Ended'), ('cancelled', 'Election Cancelled'), ('candidate_added', 'Candidate Added'), ('candidate_removed', 'Candidate Removed'), ('voter_blocked', 'Voter Blocked'), ('vote_flagged', 'Vote Flagged'), ('result_published', 'Result Published')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what changed')),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON)')),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='voting_app.election')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election Audit Log',
                'verbose_name_plural': 'Election Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempt', models.CharField(blank=True, help_text='Stores username even on failed attempts', max_length=150)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='success', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, help_text='e.g. Mobile / Desktop / Tablet', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Activity Log',
                'verbose_name_plural': 'Login Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp_hash', models.CharField(help_text='Hashed OTP — never store plain text', max_length=128)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('vote', 'Pre-Vote Verification'), ('signup', 'Signup')], default='vote', max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('aadhaar_hash', models.CharField(blank=True, help_text='Hashed Aadhaar for uniqueness check (never store raw)', max_length=64)),
                ('verification_type', models.CharField(choices=[('none', 'Not Verified'), ('otp', 'OTP Verified'), ('face', 'Face Verified'), ('manual', 'Manually Verified by Admin')], default='none', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False, help_text='Admin can block suspicious voters')),
                ('block_reason', models.TextField(blank=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('last_user_agent', models.TextField(blank=True, help_text='Browser/device of last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voter Profile',
                'verbose_name_plural': 'Voter Profiles',
            },
        ),
    ]
