# Generated by Django 6.0.2 on 2026-04-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_alter_candidate_options_alter_election_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting_app.election'),
            preserve_default=False,
        ),
    ]
